name: Deploy Laract After Build to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Upload full Laract project (kecuali public)
      - name: Upload Laract except public
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".,!public"
          target: "/home/${{ secrets.SSH_USERNAME }}/my-profile"
          rm: false
          strip_components: 0

      # Upload only public folder ke public_html
      - name: Upload public folder contents
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "public/*,!public/index.php"
          target: "/home/${{ secrets.SSH_USERNAME }}/public_html"
          strip_components: 1
          rm: false